# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 18:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('entity_type', models.PositiveIntegerField(choices=[(1, 'عام'), (2, 'خاص'), (3, 'أهلي')], default=1)),
                ('study_type', models.PositiveIntegerField(choices=[(1, 'فصول دراسية'), (2, 'ساعات معتمدة'), (3, 'غير ذلك')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('entity_type', models.PositiveIntegerField(choices=[(1, 'عام'), (2, 'خاص'), (3, 'أهلي')], default=1)),
                ('study_type', models.PositiveIntegerField(choices=[(1, 'فصول دراسية'), (2, 'ساعات معتمدة'), (3, 'غير ذلك')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SVProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[\\u0621-\\u064Aa-zA-Z][\\u0621-\\u064Aa-zA-Z0-9]*([ ]?[\\u0621-\\u064Aa-zA-Z0-9]+)+$', 'Name cannot start with number, should consist of characters.')])),
                ('desc', models.TextField()),
                ('logo', models.ImageField(default='doctor.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('entity_type', models.PositiveIntegerField(choices=[(1, 'عام'), (2, 'خاص'), (3, 'أهلي')], default=1)),
                ('study_type', models.PositiveIntegerField(choices=[(1, 'فصول دراسية'), (2, 'ساعات معتمدة'), (3, 'غير ذلك')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'ذكر'), (2, 'أنثى'), (3, 'غير ذلك')], default=3)),
                ('count_of_posts', models.IntegerField(default=0)),
                ('count_of_replies', models.IntegerField(default=0)),
                ('academic_stats', models.PositiveIntegerField(choices=[(1, 'ناجح'), (2, 'راسب'), (3, 'ناجح بمواد'), (4, 'تحشسن مجموع')], default=1)),
                ('last_active_device', models.CharField(max_length=200)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart_users', to='users.Department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fac_users', to='users.Faculty')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uni_users', to='users.University')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='users.University'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.Faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.SVProfile'),
        ),
    ]
