# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_topic_professors'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='headmaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_faculties', to='cms.Professor'),
        ),
        migrations.AddField(
            model_name='university',
            name='headmaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_universities', to='cms.Professor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(to='cms.Topic'),
        ),
    ]
