# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='bio',
            field=models.CharField(default='no data initialized', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='uni_type',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
