# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170501_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='bio',
            field=models.CharField(default='no data initialized', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='headmaster',
            field=models.CharField(default='Professors name', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default='no data initialized', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='bio',
            field=models.CharField(default='no data initialized', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='headmaster',
            field=models.CharField(default='Professors name', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='location',
            field=models.CharField(default='no data initialized', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
