# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170602_1821'),
        ('users', '0011_auto_20170517_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(to='cms.Topic'),
        ),
    ]
