# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(null=True, to='cms.Topic'),
        ),
    ]
