# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 19:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_auto_20170517_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9]*[ ]?[a-zA-Z0-9]+$', 'Name cannot start with number, should consist of characters.')])),
                ('desc', models.CharField(max_length=400)),
                ('term', models.PositiveIntegerField(choices=[(1, 'First term'), (2, 'Second term'), (3, 'Summer')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.Department')),
            ],
        ),
    ]
