# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 14:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170802_0915'),
        ('cms', '0004_auto_20170802_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.TextField()),
                ('places', models.TextField()),
                ('off_days', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('json', models.TextField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='users.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='topictable',
            name='dates',
        ),
        migrations.AlterField(
            model_name='topictable',
            name='json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topictable',
            name='places',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topictable',
            name='topics',
            field=models.TextField(),
        ),
    ]
