# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0005_auto_20170807_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=200, validators=[django.core.validators.RegexValidator('^[\\u0621-\\u064Aa-zA-Z][\\u0621-\\u064Aa-zA-Z0-9]*([ ]?[\\u0621-\\u064Aa-zA-Z0-9]+)+$', 'Name cannot start with number, should consist of characters.')])),
                ('content', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')])),
                ('link', models.URLField(unique=True)),
                ('year', models.DateField()),
                ('term', models.PositiveIntegerField(choices=[(1, 'First term'), (2, 'Second term'), (3, 'Summer')])),
                ('content_type', models.PositiveIntegerField(choices=[(1, 'Lecture'), (2, 'Asset'), (3, 'Task')])),
                ('week_number', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Rejected'), (3, 'Accepted')], default=1)),
                ('supervisior_id', models.PositiveIntegerField(blank=True)),
                ('deadline', models.DateField(blank=True, default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_materials', to='cms.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='material_ptr',
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.CharField(default=1, max_length=500, validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.PositiveIntegerField(choices=[(1, 'Lecture'), (2, 'Asset'), (3, 'Task')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(default=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='N/A', max_length=200, validators=[django.core.validators.RegexValidator('^[\\u0621-\\u064Aa-zA-Z][\\u0621-\\u064Aa-zA-Z0-9]*([ ]?[\\u0621-\\u064Aa-zA-Z0-9]+)+$', 'Name cannot start with number, should consist of characters.')]),
        ),
        migrations.AddField(
            model_name='task',
            name='term',
            field=models.PositiveIntegerField(choices=[(1, 'First term'), (2, 'Second term'), (3, 'Summer')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_tasks', to='cms.Topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='year',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
