# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170629_1548'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0003_topic_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=200)),
                ('content', models.CharField(default='N/A', max_length=500)),
                ('link', models.URLField()),
                ('year', models.DateField(auto_now_add=True)),
                ('term', models.PositiveIntegerField(choices=[(1, 'First term'), (2, 'Second term'), (3, 'Summer')])),
                ('contet_type', models.PositiveIntegerField(choices=[(1, 'Lecture'), (2, 'Asset')])),
                ('week_number', models.PositiveIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_materials', to='users.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
