# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 13:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(default='N/A', max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9]*([ ]?[a-zA-Z0-9]+)+$', 'Name cannot start with number, should consist of characters.')]),
        ),
        migrations.AlterField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_materials', to='cms.Topic'),
        ),
        migrations.AlterField(
            model_name='material',
            name='year',
            field=models.DateField(),
        ),
    ]
