# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170630_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='contet_type',
            new_name='content_type',
        ),
    ]
