# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170702_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
