# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='linkedn',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
