# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170710_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='linkedn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
