# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20170712_1050'),
    ]

