# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 14:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20170712_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=200)),
                ('topics', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=200)),
                ('off_days', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('json', models.CharField(max_length=200)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='cms.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
