# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20170730_1541'),
    ]
