# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_topic_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topictable',
            name='dates',
        ),
    ]
