# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_topictable_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictable',
            name='json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topictable',
            name='places',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topictable',
            name='topics',
            field=models.TextField(),
        ),
    ]
