# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Material')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Rejected'), (3, 'Accepted')])),
                ('supervisior_id', models.PositiveIntegerField()),
            ],
            bases=('cms.material',),
        ),
    ]
