# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_usercontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Rejected'), (3, 'Accepted')], default=1),
        ),
    ]
