# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_usercontribution_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='deadline',
            field=models.DateField(blank=True, default=False),
        ),
    ]
