# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20170809_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='supervisior_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
