# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170810_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='professor',
            field=models.ManyToManyField(related_name='primary_materials', to='cms.Professor'),
        ),
        migrations.AddField(
            model_name='task',
            name='professor',
            field=models.ManyToManyField(related_name='primary_tasks', to='cms.Professor'),
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='professor',
            field=models.ManyToManyField(related_name='secondary_materials', to='cms.Professor'),
        ),
    ]
