# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')]),
        ),
    ]
