# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='supervisior_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='supervisior_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
