# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20170904_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 4, 19, 41, 57, 704029)),
        ),
    ]
