# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20170904_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 4, 19, 44, 0, 986876, tzinfo=utc)),
        ),
    ]
