# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20170904_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
