# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 16:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170629_1548'),
        ('cms', '0015_auto_20170904_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=200, validators=[django.core.validators.RegexValidator('^[\\u0621-\\u064Aa-zA-Z][\\u0621-\\u064Aa-zA-Z0-9]*([ ]?[\\u0621-\\u064Aa-zA-Z0-9]+)+$', 'Name cannot start with number, should consist of characters.')])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Material Description should be more than 50 characters.')])),
                ('link', models.URLField(unique=True)),
                ('year', models.DateField(auto_now=True)),
                ('term', models.PositiveIntegerField(choices=[(1, 'First term'), (2, 'Second term'), (3, 'Summer')])),
                ('content_type', models.PositiveIntegerField(choices=[(1, 'Lecture'), (2, 'Asset'), (3, 'Task')])),
                ('week_number', models.PositiveIntegerField()),
                ('all_app', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_events', to='users.Department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_events', to='users.Faculty')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_events', to='users.University')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
