# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170907_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_events', to='users.Faculty'),
        ),
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_events', to='users.University'),
        ),
    ]
