# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 19:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20170908_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, 'Event description should not be more than 300 characters.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
