# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20170919_2120'),
        ('cms', '0021_auto_20170920_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='department',
        ),
        migrations.AddField(
            model_name='topic',
            name='department',
            field=models.ManyToManyField(related_name='topics', to='users.Department'),
        ),
    ]
